title: "Ogrody działkowe Montinowiec"
description: "Informacje organizacyjne, dokumenty i ogłoszenia dla działkowców."
lang: "pl-PL"
baseurl: ""
url: ""
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - ".DS_Store"
  - "._*"
  - "spotkania/.DS_Store"
  - "spotkania/23.05.2026r/.DS_Store"
  - "spotkania/23.05.2026r/6.m4a"
  - "spotkania/23.05.2026r/transcript"
